version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: best_price_scraping
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      TZ: America/Asuncion
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
